### ISSUE TITLE
Demo should have dummy content

### ISSUE THREAD

**Issue by muescha** [willcode4food/gatsby-starter-paperbase#1]
Where:
- i run the demo site on https://gatsby-starter-paperbase.netlify.com/
- i click on the left menu items

what i see:
- i see only content in at the main and authentication links

what i expect:
- some dummy content in main area on all links

**Comment by willcode4food** [comment]
The format of your issue is really helpful.  The idea was to just stub out those pages.  But I'd be happy to add some dummy content for the rest of the pages.

**Comment by willcode4food** [comment]
Added some more dummy content and can be viewed at the project URL
